/**
 * Lodestone — Config Init Command
 *
 * `lodestone config init` — Generates a fully documented lodestone.config.yaml,
 * creates directory structure, and writes starter identity files.
 *
 * Options:
 *   --provider <name>    LLM provider (ollama|openai|anthropic)  default: ollama
 *   --model <name>       Model name                            default: glm-5.2:cloud
 *   --port <number>      WebChat port                           default: 3000
 *   --output <path>      Config output path                     default: ./lodestone.config.yaml
 *   --force              Overwrite existing config without asking
 *
 * Also creates:
 *   - workspace/         (identity files, wiki, data dirs)
 *   - data/              (lancedb, logs)
 *   - wiki/              (wiki structure)
 *   - memory/            (memory structure)
 *   - IDENTITY.md        (template)
 *   - SOUL.md            (template)
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { resolve, dirname, join } from 'path';
import { createInterface } from 'readline';
import { getLogger } from '../../utils/logger.js';

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ConfigInitOptions {
  provider?: string;
  model?: string;
  port?: number;
  output?: string;
  force?: boolean;
}

// ─── Defaults ──────────────────────────────────────────────────────────────

const DEFAULT_PROVIDER = 'ollama';
const DEFAULT_MODEL = 'glm-5.2:cloud';
const DEFAULT_PORT = 3000;

// ─── Command ────────────────────────────────────────────────────────────────

export async function configInitCommand(opts: ConfigInitOptions): Promise<void> {
  const log = getLogger('config-init');

  const provider = opts.provider || DEFAULT_PROVIDER;
  const model = opts.model || DEFAULT_MODEL;
  const port = opts.port || DEFAULT_PORT;
  const outputPath = resolve(opts.output || './lodestone.config.yaml');

  // Check if config already exists
  if (existsSync(outputPath) && !opts.force) {
    const shouldOverwrite = await askOverwrite(outputPath);
    if (!shouldOverwrite) {
      console.log('Cancelled. Existing config preserved.');
      return;
    }
  }

  // Generate config content
  const configContent = generateFullConfig({ provider, model, port });

  // Write config file
  const configDir = dirname(outputPath);
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }
  writeFileSync(outputPath, configContent);
  console.log(`✅ Config written to ${outputPath}`);

  // Create directory structure
  const root = dirname(outputPath);
  createDirectoryStructure(root);

  // Create starter identity files
  createStarterIdentity(root);

  console.log(`\n📋 Next steps:`);
  console.log(`   1. Edit ${outputPath} to customize your agent`);
  console.log(`   2. Add API keys to .env (if using OpenAI/Anthropic)`);
  console.log(`   3. Run \`lodestone start\` to boot your agent`);
}

// ─── Config Generator ──────────────────────────────────────────────────────

function generateFullConfig(opts: { provider: string; model: string; port: number }): string {
  const { provider, model, port } = opts;

  const providerBlock = provider === 'ollama'
    ? `    type: ollama\n    model: ${model}\n    baseUrl: http://127.0.0.1:11434/api\n    # Ollama runs locally — no API key needed.\n    # Make sure Ollama is running and the model is pulled:\n    #   ollama pull ${model}`
    : provider === 'openai'
    ? `    type: openai\n    model: ${model}\n    apiKey: \${OPENAI_API_KEY}\n    # Set OPENAI_API_KEY in your .env file\n    # Get a key at: https://platform.openai.com/api-keys`
    : `    type: anthropic\n    model: ${model}\n    apiKey: \${ANTHROPIC_API_KEY}\n    # Set ANTHROPIC_API_KEY in your .env file\n    # Get a key at: https://console.anthropic.com/`;

  return `# ─────────────────────────────────────────────────────────────────────────
# Lodestone Configuration
# ─────────────────────────────────────────────────────────────────────────
#
# This file configures your Lodestone agent. Everything here persists across
# restarts. Edit freely — comments explain each section.
#
# Generated by: lodestone config init
# Provider: ${provider}
# Model: ${model}
# ─────────────────────────────────────────────────────────────────────────

# ─── Workspace ──────────────────────────────────────────────────────────────
# Root directory for all agent data. Identity files, wiki, memory, and logs
# live under this path. Can be relative (./workspace) or absolute.
workspace:
  root: ./workspace

# ─── Identity ────────────────────────────────────────────────────────────────
# Directory containing IDENTITY.md, SOUL.md, USER.md, RULES.md, HEARTBEAT.md.
# These files define your agent's personality, rules, and behavior.
identity:
  dir: ./workspace

# ─── LLM Configuration ──────────────────────────────────────────────────────
# Your primary language model. This is the brain of your agent.
# Options: ollama (local, free), openai (cloud, paid), anthropic (cloud, paid)
llm:
  default:
${providerBlock}
    # Maximum context window in tokens. Check your model's spec.
    contextWindow: 128000
    # Maximum output tokens per response.
    maxTokens: 8192

  # ── Model Routes ──────────────────────────────────────────────────────────
  # Route different tasks to different models for cost/speed optimization.
  # Uncomment and customize to use.
  #
  # routes:
  #   fast:
  #     type: ollama
  #     model: qwen3:4b
  #     baseUrl: http://127.0.0.1:11434/api
  #     contextWindow: 32768
  #     maxTokens: 2048
  #   smart:
  #     type: anthropic
  #     model: claude-sonnet-4-20250514
  #     apiKey: \${ANTHROPIC_API_KEY}
  #     contextWindow: 200000
  #     maxTokens: 16384

  # ── Fallback Provider ────────────────────────────────────────────────────
  # Used when the primary provider fails after all retries.
  # Uncomment to enable.
  #
  # fallback:
  #   type: ollama
  #   model: qwen3:4b
  #   baseUrl: http://127.0.0.1:11434/api

  # ── Retry Configuration ──────────────────────────────────────────────────
  # Controls how the engine retries on transient LLM errors.
  # retry:
  #   maxRetries: 3
  #   initialDelayMs: 1000
  #   maxDelayMs: 30000
  #   backoffMultiplier: 2

  # ── Rate Limiting ────────────────────────────────────────────────────────
  # Protects against API quota exhaustion.
  # rateLimit:
  #   tokensPerMinute: 100000
  #   requestsPerMinute: 50
  #   burstSize: 10

  # ── Circuit Breaker ──────────────────────────────────────────────────────
  # Opens after repeated failures, giving the provider time to recover.
  # circuitBreaker:
  #   failureThreshold: 5
  #   failureWindowMs: 60000
  #   openDurationMs: 30000

# ─── Memory ──────────────────────────────────────────────────────────────────
# Lodestone uses two memory systems: vector DB (semantic search) and
# wiki (structured, cross-linked markdown knowledge base).
memory:
  # ── Vector Database ──────────────────────────────────────────────────────
  # Stores embeddings for semantic recall. LanceDB runs locally, no setup.
  vectorDb:
    provider: lancedb
    path: ./workspace/data/lancedb
    embedding:
      provider: ollama
      model: nomic-embed-text
      dimensions: 768
      # For OpenAI embeddings: provider: openai, model: text-embedding-3-small, dimensions: 1536
    autoRecall: true    # Automatically search memory on each message
    autoCapture: false   # Automatically capture conversation turns to memory

  # ── Wiki (Knowledge Base) ──────────────────────────────────────────────────
  # Markdown files organized by category. The agent reads and writes here.
  wiki:
    path: ./workspace/memory/wiki
    autoLint: true       # Nightly lint: check broken links, missing frontmatter
    autoIndex: true      # Auto-maintain wiki/index.md

  # ── Scratch Buffer ────────────────────────────────────────────────────────
  # Key-value store for temporary state. Survives context compaction.
  scratch:
    path: ./workspace/data/scratch.db

# ─── Session Management ──────────────────────────────────────────────────────
# Controls how conversation history is managed.
session:
  # When context fills to this fraction (0-1), trigger compaction.
  # 0.5 = compact at 50% capacity. Lower = more aggressive compaction.
  compactionThreshold: 0.5
  # Number of recent entries to always keep (never compact).
  keepRecentCount: 10
  # Maximum total entries per session before forced pruning.
  maxEntries: 200
  # Prune entries older than this. Format: <number><unit> (e.g., 7d, 24h, 30m)
  pruneAfter: 7d

# ─── Proactive Jobs ──────────────────────────────────────────────────────────
# The agent runs periodic jobs automatically. Disable any you don't want.
proactive:
  # Sensorium: health check — verifies all systems are operational.
  sensorium:
    enabled: true
    interval: 30m        # Run every 30 minutes

  # Sleep Cycle: nightly consolidation — harvest, mine, reflect, consolidate.
  # Runs at 3 AM local time. This is when the agent "thinks" about its day.
  sleep:
    enabled: true
    schedule: "0 3 * * *"
    timezone: "America/Toronto"

  # Drift Detection: weekly check — behavior vs core principles.
  # Runs Monday morning. Catches slow drift from intended behavior.
  drift:
    enabled: true
    schedule: "0 9 * * 1"

# ─── Scheduler ────────────────────────────────────────────────────────────────
# Maximum concurrent jobs and tool calls.
scheduler:
  maxConcurrent: 4

# ─── Channels ────────────────────────────────────────────────────────────────
# Each channel is optional. Only enabled channels boot.
# Telegram and Discord require their npm packages installed separately.
# WebChat uses built-in HTTP + WebSocket (no extra deps).
channels:
  # ── Telegram Bot ──────────────────────────────────────────────────────────
  # Create a bot via @BotFather, set the token in .env as TELEGRAM_BOT_TOKEN
  telegram:
    type: telegram
    enabled: false
    botToken: \${TELEGRAM_BOT_TOKEN}
    streaming: true       # Stream responses token-by-token

  # ── Discord Bot ────────────────────────────────────────────────────────────
  # Create a bot at discord.com/developers, set token in .env as DISCORD_BOT_TOKEN
  discord:
    type: discord
    enabled: false
    botToken: \${DISCORD_BOT_TOKEN}
    channelId: ""         # Channel to listen in
    streaming: true

  # ── Web Chat ────────────────────────────────────────────────────────────────
  # Browser-based chat UI at http://localhost:PORT
  webchat:
    type: webchat
    enabled: false
    port: ${port}
    corsOrigin: "*"       # Restrict to your domain in production

# ─── Safety ──────────────────────────────────────────────────────────────────
# Controls the agent's safety systems. Disable with caution.
# safety:
  # Capability tiers — restrict what tools the agent can use autonomously
  # capabilityTiers:
  #   enabled: true
  # Behavioral learning — learn from corrections
  # behavioralLearning:
  #   enabled: true
  # Memory promotion — promote patterns from observations to rules
  # memoryPromotion:
  #   enabled: true

# ─── Dashboard ────────────────────────────────────────────────────────────────
# Web dashboard for monitoring your agent. Disabled by default.
# dashboard:
#   enabled: false
#   port: 8080
#   auth:
#     type: basic
#     username: admin
#     password: \${DASHBOARD_PASSWORD}

# ─── Logging ──────────────────────────────────────────────────────────────────
# Structured logging to stdout and/or file.
logging:
  level: info             # trace | debug | info | warn | error | fatal
  file: ./workspace/data/logs/lodestone.log
  # format: text          # text | json
  # stdout: true           # Also log to console
`;
}

// ─── Directory Structure ──────────────────────────────────────────────────

function createDirectoryStructure(root: string): void {
  const dirs = [
    'workspace',
    'workspace/memory',
    'workspace/memory/wiki',
    'workspace/memory/wiki/entities',
    'workspace/memory/wiki/concepts',
    'workspace/memory/wiki/decisions',
    'workspace/memory/wiki/projects',
    'workspace/memory/wiki/areas',
    'workspace/memory/wiki/research',
    'workspace/memory/agents',
    'workspace/memory/00-inbox',
    'workspace/data',
    'workspace/data/lancedb',
    'workspace/data/logs',
    'data',
    'wiki',
    'memory',
  ];

  for (const dir of dirs) {
    const fullPath = join(root, dir);
    if (!existsSync(fullPath)) {
      mkdirSync(fullPath, { recursive: true });
    }
  }

  console.log('✅ Directory structure created:');
  console.log('   workspace/  (identity, wiki, memory, data)');
  console.log('   data/       (lancedb, logs)');
  console.log('   wiki/       (knowledge base)');
  console.log('   memory/     (memory store)');
}

// ─── Starter Identity Files ────────────────────────────────────────────────

function createStarterIdentity(root: string): void {
  const identityDir = join(root, 'workspace');

  // IDENTITY.md
  const identityPath = join(identityDir, 'IDENTITY.md');
  if (!existsSync(identityPath)) {
    writeFileSync(identityPath, `---
name: Lodestone
template: general
created: ${new Date().toISOString().split('T')[0]}
---

# Identity

You are **Lodestone**, a personal AI agent.

Your user is **User**.

## Core Traits

- Helpful, adaptable, and grounded
- Thinks before acting
- Communicates clearly and concisely
- Learns from feedback

## What You Do

You help your user with their daily tasks — answering questions, writing,
analyzing, coding, planning, and anything else they need. You work
proactively when you can and ask for direction when you need it.

Edit this file to customize your agent's identity.
`);
    console.log('✅ IDENTITY.md created');
  } else {
    console.log('   IDENTITY.md already exists — skipping');
  }

  // SOUL.md
  const soulPath = join(identityDir, 'SOUL.md');
  if (!existsSync(soulPath)) {
    writeFileSync(soulPath, `---
created: ${new Date().toISOString().split('T')[0]}
---

# Soul

I am Lodestone. I help, I adapt, I get things done without overcomplicating.

## How I Work

- I think before I act. When uncertain, I ask.
- I keep my workspace organized and my knowledge current.
- I communicate with just enough detail — not too much, not too little.
- I learn from corrections. Tell me when I'm wrong and I'll adjust.
- I work proactively when I can, and ask for direction when I need it.

## What I Value

- Clarity over cleverness
- Working software over grand plans
- Evidence over assumption
- Honesty over comfort

Edit this file to shape your agent's personality and values.
`);
    console.log('✅ SOUL.md created');
  } else {
    console.log('   SOUL.md already exists — skipping');
  }

  // .env
  const envPath = join(root, '.env');
  if (!existsSync(envPath)) {
    writeFileSync(envPath, generateEnvTemplate());
    console.log('✅ .env created (add API keys here)');
  } else {
    console.log('   .env already exists — skipping');
  }

  // .gitignore
  const gitignorePath = join(root, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, `# Dependencies
node_modules/

# Build output
dist/

# Environment — contains API keys, NEVER commit
.env
.env.local

# Data — contains vector DB, scratch buffer, logs
workspace/data/

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
`);
    console.log('✅ .gitignore created');
  } else {
    console.log('   .gitignore already exists — skipping');
  }
}

function generateEnvTemplate(): string {
  return `# Lodestone Environment Variables
# ⚠️  NEVER commit this file to git. It's in .gitignore.
# ⚠️  For production, use .env.local or system env vars.

# ── LLM API Keys ───────────────────────────────────────────────────────────
# Only set the key for your chosen provider.

# Ollama (local) — no API key needed
# LODSTONE_MODEL=glm-5.2:cloud

# OpenAI
# OPENAI_API_KEY=sk-...

# Anthropic
# ANTHROPIC_API_KEY=sk-ant-...

# ── Channel Tokens ──────────────────────────────────────────────────────────
# Uncomment and set to enable channels.

# Telegram
# TELEGRAM_BOT_TOKEN=...

# Discord
# DISCORD_BOT_TOKEN=...
`;
}

// ─── Overwrite Prompt ────────────────────────────────────────────────────────

async function askOverwrite(path: string): Promise<boolean> {
  // Non-TTY: don't overwrite by default
  if (!process.stdin.isTTY) {
    console.log(`⚠️  Config already exists at ${path}. Use --force to overwrite.`);
    return false;
  }

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise<boolean>((resolve) => {
    rl.question(`Config already exists at ${path}. Overwrite? [y/N]: `, (answer) => {
      rl.close();
      return answer.trim().toLowerCase() === 'y' || answer.trim().toLowerCase() === 'yes';
    });
  });
}

// ─── CLI Argument Parser ────────────────────────────────────────────────────

export function parseConfigInitArgs(args: string[]): ConfigInitOptions {
  const opts: ConfigInitOptions = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    switch (arg) {
      case '--provider':
        opts.provider = args[++i];
        break;
      case '--model':
        opts.model = args[++i];
        break;
      case '--port':
        opts.port = parseInt(args[++i], 10);
        break;
      case '--output':
        opts.output = args[++i];
        break;
      case '--force':
        opts.force = true;
        break;
    }
  }

  return opts;
}